[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.rocket]
version = "0.5.0-rc.3"

[dependencies.rocket_dyn_templates]
version = "=0.1.0-rc.3"
features = ["tera"]
